[package]
name = "lnu-elytra"
version = "0.0.8"
edition = "2024"

license = "AGPL-3.0"
repository = "https://github.com/mcitem/lnuElytra"
description = "LNU 岭南师范学院 正方教务系统 抢课 选课工具"

include = ["/src/**/*", "/LICENSE"]

[lib]
name = "lnu_elytra"
crate-type = ["cdylib", "rlib"]

[features]
default = []
tracing = ["dep:tracing"]
blocking = ["dep:tokio"]
converter = ['dep:webvpn-converter']
reqwest_cookie_store = ["dep:reqwest_cookie_store"]

__pyo3 = [
    "dep:pyo3",
    "dep:pyo3-tracing-subscriber",
    "dep:pyo3-async-runtimes",
    "blocking",
]
__flutter = ["dep:delegate", "converter", "reqwest_cookie_store"]

[dependencies]
url = "2.5.8"
rsa = "0.10.0-rc.18"
rand = "0.10.1"
base64 = "0.22.1"
chrono = "0.4.45"
thiserror = "2.0.18"
serde = { version = "1.0.228", features = ["derive"] }
scraper = { version = "0.27.0", features = ["atomic"] }
reqwest = { version = "0.13.4", features = [
    "cookies",
    "form",
    "json",
    "query",
    "rustls",
], default-features = false }

tracing = { version = "0.1.44", optional = true }
delegate = { version = "0.13.5", optional = true }
cookie_store = "0.22.1"
reqwest_cookie_store = { version = "0.10.0", optional = true }
tokio = { version = "1.52.3", optional = true, features = ["rt-multi-thread"] }

pyo3 = { version = "0.27", optional = true }
pyo3-async-runtimes = { version = "0.27", features = [
    "attributes",
    "tokio-runtime",
], optional = true }
pyo3-tracing-subscriber = { version = "0.4.0", features = [
    "stubs",
], optional = true }

webvpn-converter = { git = "https://github.com/mcitem/webvpn-converter", optional = true }


[dev-dependencies]
env_logger = { version = "0.11.11" }
pyo3-stub-gen = { version = "0.23.0" }


[workspace]
resolver = "3"
members = [".", "./examples", "./mock"]
dependencies = { "lnu-elytra" = { path = "." } }
