# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "Client",
    "Course",
    "Jxb",
    "SelectCourseResponse",
]

@typing.final
class Client:
    def __new__(cls) -> Client: ...
    def login(self, username: builtins.str, password: builtins.str) -> None: ...
    def init(self) -> None: ...
    def fetch_course(self, q: builtins.str) -> Course: ...
    def select_course(self, course_id: builtins.str, course_do_id: builtins.str) -> SelectCourseResponse: ...

@typing.final
class Course:
    @property
    def xkkz_id(self) -> builtins.str: ...
    @property
    def kch_id(self) -> builtins.str: ...
    @property
    def jxb(self) -> builtins.list[Jxb]: ...
    def try_select_0(self, client: Client) -> SelectCourseResponse: ...
    def try_select_by_time(self, client: Client, q: builtins.str) -> SelectCourseResponse: ...

@typing.final
class Jxb:
    @property
    def jxb_id(self) -> builtins.str: ...
    @property
    def do_id(self) -> builtins.str: ...
    @property
    def jsxx(self) -> builtins.str: ...
    @property
    def sksj(self) -> builtins.str: ...

@typing.final
class SelectCourseResponse:
    r"""
    { flag: "1", msg: None }
    
    { flag: "0", msg: Some("对不起，当前未开放选课！") }
    
    { flag: "0", msg: Some("选课频率过高，请稍后重试！") }
    
    { flag: "0", msg: Some("一门课程只能选一个教学班，不可再选！") }
    
    { flag: "0", msg: Some("超过体育分项本学期本专业最高选课门次限制，不可选！") }
    """
    ...

