name: Rust CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          cargo check
          cargo check --no-default-features
          cargo check --all-features
          cargo check -F tracing
          cargo check -F blocking
          cargo check -F converter
          cargo check -F reqwest_cookie_store
          cargo check -F __pyo3
          cargo check -F __flutter
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          cargo build
          cargo build --no-default-features
          cargo build --all-features
          cargo build -F tracing
          cargo build -F blocking
          cargo build -F converter
          cargo build -F reqwest_cookie_store
          cargo build -F __pyo3
          cargo build -F __flutter
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          cargo test
          cargo test --no-default-features
          cargo test --all-features
          cargo test -F tracing
          cargo test -F blocking
          cargo test -F converter
          cargo test -F reqwest_cookie_store
          cargo test -F __pyo3
          cargo test -F __flutter
